comment: "VGG Parameter Set"

ckks_params:
  LogN: 16
  LogQ: [55, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]
  LogP: [61, 61, 61, 61, 61, 61, 61, 61]
  LogScale: 40
  H: 16384

boot_params:
  LogP: [61, 61, 61, 61, 61, 61, 61, 61]

orion:
  batch_size: 1
  margin: 2 # >= 1
  packing_method: advanced # [beginner, intermediate, advanced]
  
  diags_path: "../data/diagonals.h5" # "path/to/diags" | ""
  evks_path: "../data/keys.h5" # "path/to/keys" | ""
  io_mode: "none" # "load" | "save" | "none"
